CREATE DATABASE IF NOT EXISTS Apollo;

CREATE TABLE IF NOT EXISTS PersonType (
	ID CHAR(36) CHARACTER SET ASCII PRIMARY KEY,
	Name NVARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Person (
	ID CHAR(36) CHARACTER SET ASCII PRIMARY KEY,
    Username NVARCHAR(255) UNIQUE NOT NULL,
    Secret NVARCHAR(255) NOT NULL,
	Name NVARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    Address NVARCHAR(255),
    PersonTypeID CHAR(36) CHARACTER SET ASCII NOT NULL,
    FOREIGN KEY (PersonTypeID) REFERENCES PersonType(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CourseDefinition (
	ID CHAR(36) CHARACTER SET ASCII PRIMARY KEY,
	Code NVARCHAR(32) CHARACTER SET ASCII NOT NULL,
	Name NVARCHAR(255) NOT NULL,
    Description MEDIUMTEXT CHARACTER SET UTF8MB4,
    Credit INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Course (
	ID CHAR(36) CHARACTER SET ASCII PRIMARY KEY,
    CourseDefinitionID CHAR(36) CHARACTER SET ASCII,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    TeacherID CHAR(36) CHARACTER SET ASCII NOT NULL,
    FOREIGN KEY (CourseDefinitionID) REFERENCES CourseDefinition(ID) ON DELETE CASCADE,
	FOREIGN KEY (TeacherID) REFERENCES Person(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS StudentCourse (
	ID CHAR(36) CHARACTER SET ASCII PRIMARY KEY,
	StudentID CHAR(36) CHARACTER SET ASCII NOT NULL,
    CourseID CHAR(36) CHARACTER SET ASCII NOT NULL,
    Score FLOAT,
    FOREIGN KEY (StudentID) REFERENCES Person(ID) ON DELETE CASCADE,
	FOREIGN KEY (CourseID) REFERENCES Course(ID) ON DELETE CASCADE
);